### Variables Globales
@host = http://localhost:8080
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2OTQ1NjIxMywiZXhwIjoxNzY5NTQyNjEzfQ.9xkNR4Aq3pw2RliHBcSylDC1EuKdzZ2jqYwmLAOgb3Q

### 1. Buscar una carta por nombre (y guardarla si no existe)
GET {{host}}/cards/search?name=Black Lotus
Accept: {{contentType}}

> {%
    client.test("Carta encontrada - Estado 200", function() {
        client.assert(response.status === 200, "No se encontró la carta");
    });
    client.global.set("globalCardId", response.body.id);
%}

### 2. Obtener toda la biblioteca de cartas conocidas
GET {{host}}/cards/library
Accept: {{contentType}}
Authorization: Bearer {{token}}

> {%
    client.test("Biblioteca obtenida - Estado 200", function() {
        client.assert(response.status === 200, "Error al obtener la biblioteca");
    });
    client.test("Es un array", function() {
        client.assert(Array.isArray(response.body), "El cuerpo no es una lista");
    });
%}

### 3. Obtener una carta específica por ID
# Usamos el ID guardado en el paso 1
GET {{host}}/cards/{{globalCardId}}
Accept: {{contentType}}

> {%
    client.test("Obtener carta por ID - Estado 200", function() {
        client.assert(response.status === 200, "Error al obtener la carta por ID");
    });
    client.test("El nombre coincide", function() {
        // Verificamos que sea la carta que buscamos antes
        if(response.body.name) {
             client.assert(response.body.name === "Black Lotus", "El nombre no coincide");
        }
    });
%}