### Variables Globales
@host = http://localhost:8080
@contentType = application/json
@auth_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZW1vIiwiaWF0IjoxNzY5NTEwMTA1LCJleHAiOjE3Njk1OTY1MDV9.Exo1POHgHCrYHcAlaoCHEJo6fzI-oyp5Xtxcl-z5lFo
@collectionId = 1


### 1. Crear una nueva colección
POST {{host}}/collections/create
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

 {
 "name": "Segunda Colección"
 }
 > {%
     client.test("Colección creada - Estado 200", function() {
         client.assert(response.status === 200, "Error al crear colección");
     });
     client.global.set("collectionId", response.body.id);
 %}

### 2. Listar todas las colecciones del usuario
GET {{host}}/collections/all
Accept: {{contentType}}
Authorization: Bearer {{auth_token}}

> {%
    client.test("Listar colecciones - Estado 200", function () {
        client.assert(response.status === 200, "Error al listar colecciones");
    });
%}

### 3. Actualizar el nombre de la colección
PUT {{host}}/collections/update/{{collectionId}}
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "name": "Mazo Actualizado"
}

> {%
    client.test("Colección actualizada - Estado 200", function () {
        client.assert(response.status === 200, "Error al actualizar colección");
    });
    client.test("Nombre cambiado", function () {
        client.assert(response.body.name === "Mazo Actualizado", "El nombre no cambió");
    });
%}

### 4. Eliminar la colección
DELETE {{host}}/collections/delete/{{collectionId}}
Authorization: Bearer {{auth_token}}

> {%
    client.test("Colección eliminada - Estado 200", function () {
        client.assert(response.status === 200, "Error al eliminar colección");
    });
    client.test("Mensaje de confirmación", function () {
        client.assert(response.body.message === "Colección eliminada", "Mensaje incorrecto");
    });
%}